# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50021f1d1c67e9b48921f24e269448b890c9a14de9b4df0536cbb10ecd55e7a76bdea5c8fef47291f4940f8bf7ecc52e4bed9ea98c3f470d244fe419fc83ef91

test:
  secret_key_base: f69293ddf296007918873773170f5aaf60ab5672dd3af8e7d432fedbc4aefb6a57e794a7e0d3e88b60478cf85fb39fddb18a99a6a4fbed6c08e7ae078c647959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
